### PR TITLE
Pep8 Setup for codeclimate, pylint setup for CI/CD, and some clean up stuff.

### PR DESCRIPTION
**Pull request by utx0**

### CODE REVIEW

**Comment by mikenew** [comment]
I don't think you can take out unittest2 as it is the test framework I'm using

**Comment by utx0** [comment]
unittest is different from unisttest2. unittest is build into standard python, unittest2 is a package for project going from python2 > python3. 

To test this load up a Terminal window and type in the following commands:

    $python3
    >import unittest
    >unittest

You should get something similar to the following: 

   <module 'unittest' from '/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/__init__.py'>

**Comment by mikenew** [comment]
OK cool .... let's merge ....

**Comment by mikenew** [comment]
hmmm not sure how to resolve the conflict in pipfile ..... also I noticed I've installed scipy into the dev area rather than for production

**Comment by utx0** [comment]
ill fix it. Give me a sec. Dont pull for a bit.

**Pull request merged**
